### PR TITLE
Added optional 'override' for specification customization

### PR DESCRIPTION
**Pull request by ajturner**
Developers will need to have fine-grained control over some elements of the chart but should not have to fork it just to change colors or other simple options. So you can now do things like:

```javascript
    //create a cedar chart
    var chart = new Cedar({"specification":"../data/templates/bar-chart-spec.json"});

    chart.override = {
      "height": 400,
      "marks": [{"properties": {
        "hover": {"fill": {"r": {"value": 210}, "g": {"value": 105}, "b":{"value": 30}}},
        "update": {"fill": {"value": "#c15000"}}}}]};
```

- Cleaned up pie chart labels a little bit - still need work
- Fixed scatterplot color labels

esri_cedar

### CODE REVIEW

**Comment by ajturner** [comment]
ping @dbouwman @benheb

**Comment by dbouwman** [comment]
While we can do something like this, the more common pattern would be to simply modify the template object before passing it into Cedar, or if they don't want to fetch it themselves, then use the .specification property to access the template

```
//change the template
chart.specification.template.marks =  [
      {"properties": {
        "hover": {"fill": {"value": "orange"}},
        "update": {"fill": {"value": "#c15000"}}}},
      {"properties": {
        "enter": {"fill": {"value": "white"}}}}
    ]};
```
If we wanted to do an "overrides", we could use _.extend(base,new), with the caveat that this will only "extend" over the first level of keys. http://underscorejs.org/#extend

Thoughts @benheb / @mjuniper ?

**Comment by benheb** [comment]
I'm not sure I have a real preference, but I like just modifying the template off .specification and passing that to Cedar, 'makes sense' to me as a developer.

**Comment by ajturner** [comment]
Part of the goal was appearing Cedar as a standard chart library where user can specify colors, fonts, width, height etc. We have to expose a little of Veg, but this should be minimal.

Can it all happen in one `new Cedar` call where the Dev doesn't have to do any callbacks for simple style modifications? 

For an advanced Dev, they can definitely dive into the object afterwards, but hope it can be simple for the simple cases that need standard controls.

**Comment by benheb** [comment]
First of all, I'm confused because I already see "chart.override" locally in the demos in my branch but this PR isn't merged? Where did that come from? 

I may be missing what the real issue is there, but to me I would think it'd be something like: 

`var chart = new Cedar({
  "specification":"../data/templates/bar-chart-spec.json",
  "height": 400,
  "color": "#c15000",
  "hover": "#2980b9"
});`

We remove the complexity of "marks" and "properties" and just know what to do with hover and color properties passed in. No?

**Comment by ajturner** [comment]
I think that I messed up a push - sorry.

As for we may not want it to be that flattened, charts may have multiple marks, including text, and the Dev may override any of those.

We could assume that by default it's the first mark. However I think likely this would quickly confuse once the Dev wanted to do something slightly different. What about stroke color, size, opacity, etc.

The alternative is to make all these explicit as optional inputs with defaults.

**Comment by dbouwman** [comment]
The point of leveraging vega is that it provides a "standard grammar" for describing the visualization - which means the complexity of marks etc, but that's the trade-off of using this standard. 

That said, one option I was mulling while dodging trees, was the idea that for basic (bar/scatter/line/pie) charts, we could have a flatter api. Doing this will involve adding another layer of indirection in the form of chart objects which know how to map a flat hash of settings into the vega spec hash. 

All other visualizations would use a more generic chart object which simply acts how the api acts today - get/set the template.

Again though - I'd hesitate to start adding this "convenience" layer until more developers have played with it. If we hide the "vega-ness", and build out our own api over "all-the-visualizations" we have simply re-built a chart library that happens to have a dependency on vega.

Having well documented example templates should mitigate the "gah - I need the chart to be red, but there is no .color() property!" concerns.

**Comment by ajturner** [comment]
Agreed. As a next step we should build out that first set of default templates: (should move to an issue)

- Bar: numeric, ordinal, temporal on either axis
- line: temporal vs Numeric, aggregated temporal vs binned stats (count of categories by time period)
- Pyramid (facet) chart that Location Analytics will need
- Scatter
- Box plot

Let's hold off on pie - that will be problematic

**Pull request closed without merging**
